/*
    Even Fibonacci Numbers
     
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

                1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    https://projecteuler.net/problem=2
*/

#include <stdio.h>

int main(void)
{
    int count, c;
    int a = 1;
    int b = 2;
    int sum = 2;
    
    for (count = 1; b < 4000000; count++)
    {
        c = a;
        a = b;
        b = c + a;
        if (count%3 == 0) //Every third Fibonacci number is even
            sum = sum + b;           
    }
    
    printf("%i", sum);
}
